### ISSUE TITLE
plans for v2 ?

### ISSUE THREAD

**Issue by davephillips** [scanner-darkly/vcv-collection-one#6] opened 2021-11-17 20:41 UTC
Hi ! Just checking if you plan to update Orca's Heart to the VCV Rack v2 SDK.

[Edit]  I built it with only the change in plugin.json but have yet to test. It loaded without problems, will test later this evening.

**Comment by scanner-darkly** [comment] 2021-11-20 20:46
yeah, planning to update it - likely will be a month or two before i get to it though.
if you get to it sooner please feel free to do a pull request!

**Comment by biggnome** [comment] 2021-12-19 22:30
I'm still getting a segmentation fault upon startup (most of the time with the binary plugin from the library; consistently with a manual compile) with Windows 10 and Rack 2.0.3/2.0.3b.
[Edit: confirmed on Manjaro Linux running Rack 2.0.3 as well]

Also, a couple of minor UI things--there's a space missing after the plus in "+Octave B"; and--just asking as a favor for the sake of my own fussiness--could the controls with discrete values (i.e., length, speed, algo x/y, shift, and space) have snap enabled?

By the way, thanks a lot for updating this--I've been really missing Orca's Heart since the release of v2.

**Comment by scanner-darkly** [comment] 2021-12-20 19:33
thank you - others also reported the issue, will troubleshoot this week.
re: snap - good suggestion, i created a separate issue to track it: https://github.com/scanner-darkly/vcv-collection-one/issues/9

**Comment by scanner-darkly** [comment] 2021-12-26 01:36
@biggnome - could you give this version a try? it should fix the crash, and i also implemented your suggestion.

**Comment by biggnome** [comment] 2021-12-26 02:06
No crashes so far in either W10 and Manjaro, both running Rack 2.0.4. I'll let you know if I run into any issues, but it seems stable. Fingers crossed (and thank you!)
[Edit: still totally solid, and verified in Debian as well.]

**Comment by scanner-darkly** [comment] 2021-12-26 23:21
the crash issue is fixed in 7f6b993fa7880f1b2aae04e5f3875ae3b84b4de3

**Closed as completed by scanner-darkly** 2021-12-26 23:21 UTC
